# Generated by Django 5.0.7 on 2024-11-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=3, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
