# Generated by Django 5.0.7 on 2024-09-13 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('finalizado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=1)),
                ('imp_diag', models.CharField(blank=True, max_length=50, null=True)),
                ('pieza', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('entidad', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('hc', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cid', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('raza', models.CharField(blank=True, choices=[('B', 'Blanca'), ('N', 'Negra')], max_length=1, null=True)),
                ('es_fallecido', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Necropsia',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('certif_defuncion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=50, null=True)),
                ('habito_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('analisis_por_cavidades', models.CharField(blank=True, max_length=50, null=True)),
                ('analisis_por_aparatos', models.CharField(blank=True, max_length=50, null=True)),
                ('hallazgos', models.CharField(blank=True, max_length=50, null=True)),
                ('epicrisis', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_macro', models.CharField(blank=True, max_length=50, null=True)),
                ('no_fragmentos', models.IntegerField(blank=True, null=True)),
                ('no_bloques', models.IntegerField(blank=True, null=True)),
                ('exist_resto', models.BooleanField(blank=True, null=True)),
                ('descripcion_micro', models.CharField(blank=True, max_length=50, null=True)),
                ('malignidad', models.BooleanField(blank=True, null=True)),
                ('no_laminas', models.IntegerField(blank=True, null=True)),
                ('no_cr', models.IntegerField(blank=True, null=True)),
                ('no_ce', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
