# Generated by Django 5.0.7 on 2024-07-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablePatient',
            fields=[
                ('hc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cid', models.CharField(blank=True, max_length=11, null=True)),
                ('full_name', models.CharField()),
                ('age_month', models.IntegerField(blank=True, null=True)),
                ('age_year', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('race', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableStudy',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField()),
                ('imp_diag', models.TextField(blank=True, null=True)),
                ('cid_specialist', models.CharField(blank=True, max_length=11, null=True)),
                ('piece', models.CharField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('entity', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table_study',
                'managed': False,
            },
        ),
    ]
