# Generated by Django 5.0.7 on 2024-09-13 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='especialista',
            field=models.ForeignKey(db_column='especialista', limit_choices_to={'groups__name': 'LabStaffGroup'}, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudio',
            name='medico',
            field=models.ForeignKey(db_column='medico', limit_choices_to={'groups__name': 'DoctorsGroup'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Fallecido',
            fields=[
                ('hc', models.OneToOneField(db_column='hc', max_length=6, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myApp.paciente')),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('app', models.CharField(blank=True, max_length=50, null=True)),
                ('apf', models.CharField(blank=True, max_length=50, null=True)),
                ('hea', models.CharField(blank=True, max_length=50, null=True)),
                ('apgar', models.IntegerField(blank=True, null=True)),
                ('edad_gest', models.IntegerField(blank=True, null=True)),
                ('fecha_muerte', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='hc_paciente',
            field=models.ForeignKey(db_column='hc_paciente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='studies', to='myApp.paciente'),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='especialista',
            field=models.ForeignKey(db_column='especialista', limit_choices_to={'groups__name': 'LabStaffGroup'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proceso',
            name='cod_est',
            field=models.OneToOneField(blank=True, db_column='cod_est', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proceso_est', to='myApp.estudio'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='cod_necro',
            field=models.ForeignKey(blank=True, db_column='cod_necro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proceso_necro', to='myApp.necropsia'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_proceso',
            field=models.OneToOneField(db_column='id_proceso', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='myApp.proceso'),
        ),
        migrations.AddField(
            model_name='necropsia',
            name='hc_fallecido',
            field=models.ForeignKey(db_column='hc_fallecido', on_delete=django.db.models.deletion.DO_NOTHING, related_name='necropsy', to='myApp.fallecido'),
        ),
    ]
