# Generated by Django 5.0.7 on 2024-09-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_proceso_cod_est_alter_proceso_cod_necro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='diagnostico',
            name='finalizado',
        ),
        migrations.AddField(
            model_name='estudio',
            name='finalizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='hc_paciente',
            field=models.ForeignKey(db_column='hc_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='myApp.paciente'),
        ),
        migrations.AlterField(
            model_name='fallecido',
            name='hc',
            field=models.OneToOneField(db_column='hc', max_length=6, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.paciente'),
        ),
        migrations.AlterField(
            model_name='necropsia',
            name='hc_fallecido',
            field=models.ForeignKey(db_column='hc_fallecido', on_delete=django.db.models.deletion.CASCADE, related_name='necropsy', to='myApp.fallecido'),
        ),
    ]
