# Generated by Django 5.0.7 on 2024-09-28 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_hc_fallecido_necropsia_hc_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('dpto', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='proceso',
            name='cod_necro',
            field=models.OneToOneField(blank=True, db_column='cod_necro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proceso_necro', to='myApp.necropsia'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='medico',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='myApp.doctor'),
        ),
    ]
