# Generated by Django 5.0.7 on 2024-09-28 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_doctor_alter_proceso_cod_necro_alter_estudio_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='medico',
        ),
        migrations.AddField(
            model_name='estudio',
            name='doctor',
            field=models.ForeignKey(db_column='doctor', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='myApp.doctor'),
            preserve_default=False,
        ),
    ]
