# Generated by Django 5.0.7 on 2024-10-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_estudio_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='raza',
            field=models.CharField(blank=True, choices=[('B', 'Blanca'), ('N', 'Negra'), ('M', 'Mulato')], max_length=1, null=True),
        ),
    ]
